### ISSUE TITLE
Logs e Auditoria do sistema

### ISSUE THREAD

**Issue by mauriciocc** [mauriciocc/pedidos-aula#2]
Salvar alteações feitas nos registros do sistema

**Comment by MiguelSWolf** [comment]
Criada a auditoria e adicionado o script de trigger para gerar.
TODO: pensar em talvez fazer com hooks... não esta usando a plataforma muito bem usando dessa forma. 
FIXME: corrigir o createdat e updatedat que não estão sendo excluidos quando colocado timestamps false

**Comment by mauriciocc** [comment]
Implementado logs via hooks no sequelize.js
